# Generated by Django 4.2 on 2024-06-10 16:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("report", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0004_site_planning_prefix_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Planning", "Planning"),
                            ("Planning Confirmé", "Planning Confirmé"),
                            ("Raté", "Raté"),
                            ("Annulé", "Annulé"),
                        ],
                        max_length=40,
                    ),
                ),
                ("date_planning", models.DateField()),
                ("distributeur_id", models.IntegerField()),
                ("distributeur", models.CharField(max_length=255)),
                ("client_id", models.IntegerField()),
                ("client", models.CharField(max_length=255)),
                ("livraison", models.CharField(max_length=255)),
                ("observation_comm", models.TextField(blank=True, null=True)),
                ("chauffeur", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "immatriculation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("observation_logi", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.emplacement",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.fournisseur",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.site"
                    ),
                ),
                (
                    "tonnage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.tonnage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_state",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Planning", "Planning"),
                            ("Planning Confirmé", "Planning Confirmé"),
                            ("Raté", "Raté"),
                            ("Annulé", "Annulé"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("Brouillon", "Brouillon"),
                            ("Planning", "Planning"),
                            ("Planning Confirmé", "Planning Confirmé"),
                            ("Raté", "Raté"),
                            ("Annulé", "Annulé"),
                        ],
                        max_length=40,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("miss_reason", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commercial.planning",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PPlanned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "palette",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "planning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commercial.planning",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.product",
                    ),
                ),
            ],
        ),
    ]
