# Generated by Django 4.2 on 2024-06-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
        ("commercial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="chauffeur",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planning",
            name="fournisseur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.fournisseur",
            ),
        ),
    ]
