# Generated by Django 4.2 on 2024-06-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
        ("commercial", "0002_alter_planning_chauffeur_alter_planning_fournisseur"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PPlannned",
            new_name="PPlanned",
        ),
    ]
